### PR TITLE
Remove Unnecessary Comma

### PR DESCRIPTION
**Pull request by Jumblemuddle**
See https://github.com/NixOS/nixpkgs/pull/44076#issuecomment-435585917

### CODE REVIEW

**Comment by anmonteiro** [comment]
I'm afraid this is gonna be a rough and brittle path. We use Prettier to format the JavaScript files and it places trailing commas everywhere. Is using a Node.js version with support for trailing commas out of the question?

**Comment by Jumblemuddle** [comment]
I haven't experienced prettier adding commas like that to the end of function calls before. Extra commas in object definitions makes sense.

**Comment by anmonteiro** [comment]
@Jumblemuddle see https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzCEAUBnCBbOAGgAIBDAJwHMBXA2bEmAC1JhLFOuyOIHdzSAB0EBLKJQCUAbhCEQEQTBHRsyUBXIReABQoJVKUgDcIIgCayQAIwFgA1nBgBlQaTBjKyGOWpEQTGDwAGwB1JhF4bFcwOCd9CJEjCIBPZHBsVTkxbnIYbQFKPFJkVFIg7jkAK2wADwAhWwdnUgIAGTE4ErKKkGqapw8guABFagh4LvK-V3IctKtSK2Sg6EtBcjEYEPNmZAAmAAY5dYhuEIFBNPW4HKNOuXI4AEdqEUf80kLipFKpuW48CIvD4-NhBiMxhMkN5fHIYIttmZdkg9nCBCIgh4AML4IppMpBSxcOAAFUWBl+3AAvlSgA

**Comment by hlolli** [comment]
@Jumblemuddle since you're here, I'm working on the 1.9 release of lumo for nixos with a patch. We would need the patch anyway if we are targeting a release. ESLint online (if this url works) shows same error as yegortimoshenko reported

https://eslint.org/demo/#eyJ0ZXh0IjoiaWYgKCFpc0RldkJ1aWxkKSB7XG4gIHBsdWdpbnMucHVzaChcbiAgICBiYWJlbE1pbmlmeSh7XG4gICAgICBjb21tZW50czogZmFsc2UsXG4gICAgICByZW1vdmVDb25zb2xlOiB0cnVlLFxuICAgICAgcmVtb3ZlRGVidWdnZXI6IHRydWUsXG4gICAgfSksXG4gICk7XG59Iiwib3B0aW9ucyI6eyJwYXJzZXJPcHRpb25zIjp7ImVjbWFWZXJzaW9uIjo1LCJzb3VyY2VUeXBlIjoic2NyaXB0IiwiZWNtYUZlYXR1cmVzIjp7fX0sInJ1bGVzIjp7ImNvbnN0cnVjdG9yLXN1cGVyIjoyLCJmb3ItZGlyZWN0aW9uIjoyLCJnZXR0ZXItcmV0dXJuIjoyLCJuby1jYXNlLWRlY2xhcmF0aW9ucyI6Miwibm8tY2xhc3MtYXNzaWduIjoyLCJuby1jb21wYXJlLW5lZy16ZXJvIjoyLCJuby1jb25kLWFzc2lnbiI6Miwibm8tY29uc29sZSI6Miwibm8tY29uc3QtYXNzaWduIjoyLCJuby1jb25zdGFudC1jb25kaXRpb24iOjIsIm5vLWNvbnRyb2wtcmVnZXgiOjIsIm5vLWRlYnVnZ2VyIjoyLCJuby1kZWxldGUtdmFyIjoyLCJuby1kdXBlLWFyZ3MiOjIsIm5vLWR1cGUtY2xhc3MtbWVtYmVycyI6Miwibm8tZHVwZS1rZXlzIjoyLCJuby1kdXBsaWNhdGUtY2FzZSI6Miwibm8tZW1wdHktY2hhcmFjdGVyLWNsYXNzIjoyLCJuby1lbXB0eS1wYXR0ZXJuIjoyLCJuby1lbXB0eSI6Miwibm8tZXgtYXNzaWduIjoyLCJuby1leHRyYS1ib29sZWFuLWNhc3QiOjIsIm5vLWV4dHJhLXNlbWkiOjIsIm5vLWZhbGx0aHJvdWdoIjoyLCJuby1mdW5jLWFzc2lnbiI6Miwibm8tZ2xvYmFsLWFzc2lnbiI6Miwibm8taW5uZXItZGVjbGFyYXRpb25zIjoyLCJuby1pbnZhbGlkLXJlZ2V4cCI6Miwibm8taXJyZWd1bGFyLXdoaXRlc3BhY2UiOjIsIm5vLW1peGVkLXNwYWNlcy1hbmQtdGFicyI6Miwibm8tbmV3LXN5bWJvbCI6Miwibm8tb2JqLWNhbGxzIjoyLCJuby1vY3RhbCI6Miwibm8tcmVkZWNsYXJlIjoyLCJuby1yZWdleC1zcGFjZXMiOjIsIm5vLXNlbGYtYXNzaWduIjoyLCJuby1zcGFyc2UtYXJyYXlzIjoyLCJuby10aGlzLWJlZm9yZS1zdXBlciI6Miwibm8tdW5kZWYiOjIsIm5vLXVuZXhwZWN0ZWQtbXVsdGlsaW5lIjoyLCJuby11bnJlYWNoYWJsZSI6Miwibm8tdW5zYWZlLWZpbmFsbHkiOjIsIm5vLXVuc2FmZS1uZWdhdGlvbiI6Miwibm8tdW51c2VkLWxhYmVscyI6Miwibm8tdW51c2VkLXZhcnMiOjIsIm5vLXVzZWxlc3MtZXNjYXBlIjoyLCJyZXF1aXJlLXlpZWxkIjoyLCJ1c2UtaXNuYW4iOjIsInZhbGlkLXR5cGVvZiI6Mn0sImVudiI6e319fQ==

**Comment by Jumblemuddle** [comment]
> @Jumblemuddle see https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzCEAUBnCBbOAGgAIBDAJwHMBXA2bEmAC1JhLFOuyOIHdzSAB0EBLKJQCUAbhCEQEQTBHRsyUBXIReABQoJVKUgDcIIgCayQAIwFgA1nBgBlQaTBjKyGOWpEQTGDwAGwB1JhF4bFcwOCd9CJEjCIBPZHBsVTkxbnIYbQFKPFJkVFIg7jkAK2wADwAhWwdnUgIAGTE4ErKKkGqapw8guABFagh4LvK-V3IctKtSK2Sg6EtBcjEYEPNmZAAmAAY5dYhuEIFBNPW4HKNOuXI4AEdqEUf80kLipFKpuW48CIvD4-NhBiMxhMkN5fHIYIttmZdkg9nCBCIgh4AML4IppMpBSxcOAAFUWBl+3AAvlSgA

Huh, that's interesting. Do you know what versions of Node support that syntax?

**Comment by Jumblemuddle** [comment]
> @Jumblemuddle since you're here, I'm working on the 1.9 release of lumo for nixos with a patch. We would need the patch anyway if we are targeting a release. ESLint online (if this url works) shows same error as yegortimoshenko reported
> 
> https://eslint.org/demo/#eyJ0ZXh0IjoiaWYgKCFpc0RldkJ1aWxkKSB7XG4gIHBsdWdpbnMucHVzaChcbiAgICBiYWJlbE1pbmlmeSh7XG4gICAgICBjb21tZW50czogZmFsc2UsXG4gICAgICByZW1vdmVDb25zb2xlOiB0cnVlLFxuICAgICAgcmVtb3ZlRGVidWdnZXI6IHRydWUsXG4gICAgfSksXG4gICk7XG59Iiwib3B0aW9ucyI6eyJwYXJzZXJPcHRpb25zIjp7ImVjbWFWZXJzaW9uIjo1LCJzb3VyY2VUeXBlIjoic2NyaXB0IiwiZWNtYUZlYXR1cmVzIjp7fX0sInJ1bGVzIjp7ImNvbnN0cnVjdG9yLXN1cGVyIjoyLCJmb3ItZGlyZWN0aW9uIjoyLCJnZXR0ZXItcmV0dXJuIjoyLCJuby1jYXNlLWRlY2xhcmF0aW9ucyI6Miwibm8tY2xhc3MtYXNzaWduIjoyLCJuby1jb21wYXJlLW5lZy16ZXJvIjoyLCJuby1jb25kLWFzc2lnbiI6Miwibm8tY29uc29sZSI6Miwibm8tY29uc3QtYXNzaWduIjoyLCJuby1jb25zdGFudC1jb25kaXRpb24iOjIsIm5vLWNvbnRyb2wtcmVnZXgiOjIsIm5vLWRlYnVnZ2VyIjoyLCJuby1kZWxldGUtdmFyIjoyLCJuby1kdXBlLWFyZ3MiOjIsIm5vLWR1cGUtY2xhc3MtbWVtYmVycyI6Miwibm8tZHVwZS1rZXlzIjoyLCJuby1kdXBsaWNhdGUtY2FzZSI6Miwibm8tZW1wdHktY2hhcmFjdGVyLWNsYXNzIjoyLCJuby1lbXB0eS1wYXR0ZXJuIjoyLCJuby1lbXB0eSI6Miwibm8tZXgtYXNzaWduIjoyLCJuby1leHRyYS1ib29sZWFuLWNhc3QiOjIsIm5vLWV4dHJhLXNlbWkiOjIsIm5vLWZhbGx0aHJvdWdoIjoyLCJuby1mdW5jLWFzc2lnbiI6Miwibm8tZ2xvYmFsLWFzc2lnbiI6Miwibm8taW5uZXItZGVjbGFyYXRpb25zIjoyLCJuby1pbnZhbGlkLXJlZ2V4cCI6Miwibm8taXJyZWd1bGFyLXdoaXRlc3BhY2UiOjIsIm5vLW1peGVkLXNwYWNlcy1hbmQtdGFicyI6Miwibm8tbmV3LXN5bWJvbCI6Miwibm8tb2JqLWNhbGxzIjoyLCJuby1vY3RhbCI6Miwibm8tcmVkZWNsYXJlIjoyLCJuby1yZWdleC1zcGFjZXMiOjIsIm5vLXNlbGYtYXNzaWduIjoyLCJuby1zcGFyc2UtYXJyYXlzIjoyLCJuby10aGlzLWJlZm9yZS1zdXBlciI6Miwibm8tdW5kZWYiOjIsIm5vLXVuZXhwZWN0ZWQtbXVsdGlsaW5lIjoyLCJuby11bnJlYWNoYWJsZSI6Miwibm8tdW5zYWZlLWZpbmFsbHkiOjIsIm5vLXVuc2FmZS1uZWdhdGlvbiI6Miwibm8tdW51c2VkLWxhYmVscyI6Miwibm8tdW51c2VkLXZhcnMiOjIsIm5vLXVzZWxlc3MtZXNjYXBlIjoyLCJyZXF1aXJlLXlpZWxkIjoyLCJ1c2UtaXNuYW4iOjIsInZhbGlkLXR5cGVvZiI6Mn0sImVudiI6e319fQ==

Right, I figured it would be fixed in both places, so eventually the patch could be removed.

**Comment by Jumblemuddle** [comment]
It looks like `--trailing-comma es5` instead of `--trailing-comma all` removes it.
If `all` is the new way though, I'd say nixpkgs should just require the new version which supports that style.

**Comment by Jumblemuddle** [comment]
See https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Trailing_commas

**Comment by Jumblemuddle** [comment]
It looks like Node 8.2.1 is the oldest version that supports this: https://node.green/#ES2017-features-trailing-commas-in-function-syntax

**Comment by hlolli** [comment]
That explains a lot. So I think we can let the comma stay there, patch it for the dinosaurs, 1 week is a long time in politics, 1 month is a long time in js-ecosystem. Before we know it, <= node8 will get deprecated. (btw node 8.12.0 is the "current" version of nodejs on nixos, although I'm a modern person and use nodejs_10x).

**Pull request closed without merging**
