### PR TITLE
Add ns-aliases and ns-map, refer them at REPL startup

### PR DESCRIPTION
**Pull request by anmonteiro**
cc @djblue

### CODE REVIEW

**Comment by djblue** [comment]
I pulled this PR down and got auto completion working in fireplace for lumo!

Screenshot from 2019-05-01 23-50-11

I still had to:

```clojure
(in-ns 'cljs.core)
(def all-ns lumo.repl/all-ns)
(def ns-map lumo.repl/ns-map)
(def ns-aliases lumo.repl/ns-aliases)
```

but I think that's related to how I'm evaling. Thanks for putting up this PR so quickly!

**Comment by anmonteiro** [comment]
@djblue If you could clarify how you're evaling, then I can make changes to support your desired use case.

**Comment by djblue** [comment]
@anmonteiro Currently, I'm defining eval for nrepl as:

```clojure
(defn nrepl-eval [form ns] 
   (binding [cljs.js/*load-fn* lumo.repl/load
             cljs.js/*eval-fn* lumo.repl/caching-node-eval]
     (lumo.repl/eval form (find-ns ns) lumo.repl/st))) 
```

**Comment by anmonteiro** [comment]
@djblue OK, 2 things here:

1. You should probably be using `lumo.core/eval`, which sets everything up for you
2. We'll need to refer the needed functions directly in the environment. Injecting them in `cljs.core` is probably the last resort, I'll look into alternatives.


I'll have some time later today to look at this. Once all this is sorted out I'll make a release.

**Comment by djblue** [comment]
@anmonteiro When I use `lumo.core/eval`, things don't seem to work. I pushed up my work to [nrepl-cljs](https://github.com/djblue/nrepl-cljs). If you get some time, maybe you can see what I'm doing wrong. Either way this PR is useful already :100:

**Comment by djblue** [comment]
@anmonteiro do you think this PR is ready to be merged?

**Comment by anmonteiro** [comment]
@djblue sure, done.

**Pull request merged**
