### PR TITLE
issue #163 fix require bug

### PR DESCRIPTION
**Pull request by hlolli**
https://github.com/anmonteiro/lumo/issues/163

### CODE REVIEW

**Comment by anmonteiro** [comment]
Why are you downgrading dependencies as part of this PR?

**Comment by anmonteiro** [comment]
My point in #163 is that you should revert the changes to `build.boot`, not `package.json`. It's the `strip` command that actually causes the issue.

Happy to merge once you kill the changes to `package.json`.

**Comment by hlolli** [comment]
Yes, thought it was unlikely caused by the dep bumps but I took your hint too literally. Now I also failed to squeeze the last two commits... one moment.

**Comment by anmonteiro** [comment]
Don't worry about squashing. GitHub can do that for you when merging.

**Comment by hlolli** [comment]
Ok, too late :) need to learn how to do that with GitHub.

**Pull request merged**
