### PR TITLE
[Fix #341] Bump tools.reader with the unicode literal warning fix

### LINKED ISSUE #341: WARNING: cljs.core/bit-or, all arguments must be numbers
I have noticed that we have a spurious warning when doing this at the REPL:

```
cljs.user=> (int \uD7ff)
            ⬆
WARNING: cljs.core/bit-or, all arguments must be numbers, got [string number] instead. at line 1 
0
```

It does not happen in vanilla ClojureScript:

```
$ ./script/repljs 
To quit, type: :cljs/quit
cljs.user=> *clojurescript-version*
"1.9.1008"
cljs.user=> (int \uD7ff)
0
```

I will try to dig more, any hint is more than welcome!

### PR DESCRIPTION
**Pull request by arichiardi**

### CODE REVIEW

**Comment by arichiardi** [comment]
Will do

**Comment by arichiardi** [comment]
Done, there is another change we might want to include: [TRDR-51](https://github.com/clojure/tools.reader/commit/105092b84ab24b5cc57ac75efdd67cfa7d74c92e) but depending on the new release we might get this in first and then update or the other way around.

**Comment by arichiardi** [comment]
I am using this locally and I can confirm I don't receive the warning anymore.

**Comment by anmonteiro** [comment]
Feel free to merge and upgrade to the other version later

**Pull request merged**
