### PR TITLE
Expose `eval` in repl

### PR DESCRIPTION
**Pull request by moxaj**
See #146.

### CODE REVIEW

**Comment by anmonteiro** [comment]
Sorry if I wasn't clear in #146, but we don't actually want to auto-refer `eval` in the REPL. Instead we want to have a `lumo.core/eval` function that users can require (just like in https://github.com/mfikes/planck/blob/master/planck-cljs/src/planck/core.cljs#L279).

**Comment by moxaj** [comment]
My bad! For some reason I thought this was going to be a repl special ... I'll update asap.

**Comment by mfikes** [comment]
One argument for having `eval` in `lumo.core` (apart from consistency with `clojure.core`) is that it makes a little more sense for scripts that want to make use of `eval` (even though it could, it would be odd for a script to `require` the `lumo.repl` namespace).

**Comment by anmonteiro** [comment]
Thanks!

**Pull request merged**
