### PR TITLE
Add path api wrapper and tests

### PR DESCRIPTION
**Pull request by jjl**
The welcome blog post indicates an interest in having API wrappers for nodejs functionality. Accordingly, please find my first stab at a path api. If you like the look of this, I'm inclined to do a bunch more because I need them for the build tool i'm building on top of lumo anyway.

Regarding namespacing, I wasn't sure what to do, so I chose `lumo.path`, thoughts?

### CODE REVIEW

**Comment by arichiardi** [comment]
I guess this can be useful not only for `lumo` but for a bunch of other projects.
I would create a separate library or ask @yogthos if you can add it to `macchiato` 😀

Like https://github.com/macchiato-framework/macchiato-fs.

And...Good job!

**Comment by yogthos** [comment]
@arichiardi @jjl yeah I would love to add this to macchiato :)

**Comment by jjl** [comment]
@yogthos @arichiardi I am inclined to agree. Please feel free to integrate my work however you like into macchiato-fs

**Comment by yogthos** [comment]
@jjl thanks!

**Pull request closed without merging**
