### PR TITLE
Bundle aot.js.map files

### PR DESCRIPTION
**Pull request by arichiardi**
...so that the Google Closure Compiler can safely generate source maps.

### CODE REVIEW

**Comment by arichiardi** [comment]
As per Slack conversation, I need to avoid including `.map` files. Only include `.js.map` ones.

**Comment by arichiardi** [comment]
I have also detected a problem with `boot-cljs` that Juho promptly fixed and released. That is the reason of the bump.

**Comment by arichiardi** [comment]
Can rebase this  if you want tomorrow, afk now...

**Comment by anmonteiro** [comment]
just did

**Comment by arichiardi** [comment]
Oh OK, saw the merge commit there and was wondering if you wanted a cleaner history :))

**Comment by anmonteiro** [comment]
I can squash on the GH interface

**Comment by arichiardi** [comment]
Right!

**Comment by anmonteiro** [comment]
This needs some more tinkering to see if it impacts startup time

**Comment by arichiardi** [comment]
Yep, just that one file is added though.

**Pull request merged**
