### PR TITLE
Added the lumo.io namespace to completions

### PR DESCRIPTION
**Pull request by abhi18av**
Read more about this PR on  https://github.com/anmonteiro/lumo/issues/222

### CODE REVIEW

**Comment by anmonteiro** [comment]
Let's add some more namespaces here. From a quick scan, these should be public and auto-completed:

- `lumo.core`
- `lumo.classpath`
- `lumo.build.api`

**Comment by abhi18av** [comment]
@anmonteiro , sure. This namespaces have been added.

**Comment by anmonteiro** [comment]
Thanks!

**Comment by abhi18av** [comment]
No problem, this is an awesome project :)

I'm using this as a means to introduce people to Clojure-verse. Thanks for doing this :+1:

**Pull request merged**
