### PR TITLE
Propose a Lumo logo

### PR DESCRIPTION
**Pull request by leppert**
Thought it might be nice if Lumo had a fun logo. Feel free to reject if it's not your style. For posterity, the typeface is [Adobe Source Sans Pro Light](https://github.com/adobe-fonts/source-sans-pro).

For a preview, view the README on my branch:
https://github.com/leppert/lumo/tree/add-new-lumo-logo

If you do decide to merge, I'll change the `` tag to point to `anmonteiro/lumo/master` once it's merged in and the image is accessible.

### CODE REVIEW

**Comment by arichiardi** [comment]
I was thinking yesterday about this, and a reference to node, maybe the the green rhombus, might be nice, also _imho_ logo should be only text.

**Comment by jiyinyiyong** [comment]
I saw WebAssembly's logo and I like that style much better 😄

**Comment by arichiardi** [comment]
What about a mix between the ClojureScript logo and node.js logo? The `Cl` are from the former and the Js rhombus from the latter.

**Comment by anmonteiro** [comment]
I had thought about this before and I like this last idea. Something related to the Node logo with the ClojureScript colors would be what I'd go for.

Does anyone have design skills? :)

**Comment by arichiardi** [comment]
So the Node.js logo is trademarked and I asked if we could do it and they replied:

> We are not able to approve derivative logos or combination/fused logos -- such logos could be misinterpreted as endorsement or indication of a relationship.

**Comment by plexus** [comment]
Here's my attempt. It hints at both the cljs and the node logo, but it's different enough that they can't claim it as a derivative.

lumo

**Comment by arichiardi** [comment]
I kind of like it! Is it the same font as the cljs logo? I like js in the logo because it is good for visibility and clarity of what the project does. In any case I like this style.

**Comment by plexus** [comment]
No, the font is different. I don't know the exact font of the CLJS logo, but I tried some similar ones and didn't really like the result.

**Comment by plexus** [comment]
For people coming here who don't follow the slack channel:

2017-04-20-174014_402x167_scrot

**Comment by anmonteiro** [comment]
Closed in favor of https://github.com/anmonteiro/lumo/pull/194

**Pull request closed without merging**
